//
//  ViewController+Challenge33.swift
//  HashTable
//
//  Created by Manish Rathi on 27/03/2022.
//

import Foundation
/*
 389. Find the Difference
 https://leetcode.com/problems/find-the-difference/
 You are given two strings s and t.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Return the letter that was added to t.

 Example 1:
 Input: s = "abcd", t = "abcde"
 Output: "e"
 Explanation: 'e' is the letter that was added.

 Example 2:
 Input: s = "", t = "y"
 Output: "y"
 */

extension ViewController {
    func solve33() {
        print("Setting up Challenge33 input!")

        let input = "abcd"
        print("Input: \(input)")
        let output = Solution().findTheDifference(input, "abcde")
        print("Output: \(output)")
    }
}

private class Solution {
    func findTheDifference(_ s: String, _ t: String) -> Character {
        let hashMapS = hashMap(s)
        let hashMapT = hashMap(t)

        var outputChar: Character = "0"

        for (key, value) in hashMapT {
            if let valueS = hashMapS[key] {
                if valueS != value {
                    outputChar = key
                    break
                }
            } else {
                outputChar = key
                break
            }
        }

        return outputChar
    }

    private func hashMap(_ text: String) -> [Character : Int] {
        var hashMap: [Character : Int] = [:]

        for char in text {
            let hashMapValue = hashMap[char] ?? 0
            hashMap[char] = hashMapValue + 1
        }

        return hashMap
    }
}
